# ── Dockerfile Linux (GitHub Actions CI/CD uniquement) ───────────────────────
# Utilise par la pipeline .github/workflows/ci.yml sur ubuntu-latest
# NE PAS utiliser en local Windows -> voir Dockerfile (Windows containers)
# ──────────────────────────────────────────────────────────────────────────────

# Etape 1 : Build Maven
FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY mvnw mvnw.cmd pom.xml ./
COPY .mvn .mvn
RUN chmod +x ./mvnw
RUN ./mvnw dependency:go-offline -B
COPY src ./src
RUN ./mvnw package -DskipTests -B

# Etape 2 : Image finale legere
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/auth-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE=prod
ENTRYPOINT ["java", "-jar", "app.jar"]

